#pragma once

#define CAMERA_TYPE_PERSPECTIVE 0
#define CAMERA_TYPE_THIN_LENS 1
#define CAMERA_TYPE_ORTHO 2
#define CAMERA_TYPE_SPHERICAL 3
#define CAMERA_TYPE_BIT_COUNT 2
#define CAMERA_FLAGS_TYPE_BIT_OFFSET 0
#define CAMERA_FLAGS_TYPE_MASK (BIT_MASK(CAMERA_TYPE_BIT_COUNT) << CAMERA_FLAGS_TYPE_BIT_OFFSET)

#define FORCE_CAMERA_ZFAR_FINITE 1
#define FORCE_CAMERA_ZFAR_INFINITE 2

#ifndef FORCE_CAMERA_ZFAR
#define FORCE_CAMERA_ZFAR 0
#endif

#ifndef FORCE_CAMERA_APERTURE_SHAPE
#define FORCE_CAMERA_APERTURE_SHAPE 6
#endif

#ifndef FORCE_CAMERA_APERTURE_ROTATION
#define FORCE_CAMERA_APERTURE_ROTATION (0.0 * M_PI / 180.0)
#endif
