#pragma once

#define MESH_FLAG_INDEX_TYPE_UINT16 0
#define MESH_FLAG_INDEX_TYPE_UINT32 1
#define MESH_FLAG_INDEX_TYPE_UINT8  2
#define MESH_FLAG_INDEX_NONE 		3
#define MESH_FLAG_INDEX_TYPE_MASK	3

#ifndef BIND_SINGLE_MESH
#define BIND_SINGLE_MESH 0
#endif

#ifndef MESH_ACCESS
#define MESH_ACCESS
#endif

#ifndef MESH_BINDING_BASE
#define MESH_BINDING_BASE INVOCATION_DESCRIPTOR_BINDING
#endif

