#pragma once

#define ALBEDO_ALPHA_TEXTURE_SLOT 0
#define NORMAL_TEXTURE_SLOT 1
#define ROUGHNESS_TEXTURE_SLOT 2
#define METALLIC_TEXTURE_SLOT 3

#ifndef BIND_SINGLE_MATERIAL
#define BIND_SINGLE_MATERIAL 0
#endif

