#pragma once

#define ALBEDO_ALPHA_TEXTURE_SLOT 0
#define NORMAL_TEXTURE_SLOT 1
#define ROUGHNESS_TEXTURE_SLOT 2
#define METALLIC_TEXTURE_SLOT 3

#define PB_MATERIAL_DIELECTRIC_BIT (1 << 24)
#define PB_MATERIAL_DIELECTRIC_SPECRAL_APPROX_BIT (1 << 25)

#ifndef BIND_SINGLE_MATERIAL
#define BIND_SINGLE_MATERIAL 0
#endif

