#pragma once


#define SHADING_SHADOW_NONE 0
#define SHADING_SHADOW_MAP 1
#define SHADING_SHADOW_RAY_TRACE 2

#ifndef SHADING_SHADOW_METHOD
#define SHADING_SHADOW_METHOD SHADING_SHADOW_NONE
#endif

#define SHADING_NORMAL_LEVEL_GEOMETRY 0
#define SHADING_NORMAL_LEVEL_VERTEX 1
#define SHADING_NORMAL_LEVEL_TEXTURE 2

#ifndef SHADING_FORCE_MAX_NORMAL_LEVEL
#define SHADING_FORCE_MAX_NORMAL_LEVEL SHADING_NORMAL_LEVEL_TEXTURE
#endif

#ifndef SHADING_ENABLE_OPACITY_TEST
#define SHADING_ENABLE_OPACITY_TEST 1
#endif

#ifndef SHADING_FORCE_WHITE_DIFFUSE
#define SHADING_FORCE_WHITE_DIFFUSE 0
#endif

#ifndef SHADING_MATERIAL_USE_TEXTURE
#define SHADING_MATERIAL_USE_TEXTURE 1
#endif

#define SHADING_MATERIAL_READ_TEXTURES ((SHADING_MATERIAL_USE_TEXTURE != 0) && (SHADING_FORCE_WHITE_DIFFUSE == 0)) 

#define GBUFFER_MODE_FAT 0
#define GBUFFER_MODE_MINIMAL 1
