#pragma once

#define LIGHT_TYPE_POINT 0x1
#define LIGHT_TYPE_DIRECTIONAL 0x2
#define LIGHT_TYPE_SPOT 0x3
#define LIGHT_TYPE_BEAM 0x4
#define LIGHT_TYPE_MASK 0x7

#define LIGHT_ENABLE_SHADOW_MAP_BIT_INDEX 8
#define LIGHT_ENABLE_SHADOW_MAP_BIT (1 << LIGHT_ENABLE_SHADOW_MAP_BIT_INDEX)
#define LIGHT_SHADOW_MAP_BIAS_MODE_BIT_INDEX (LIGHT_ENABLE_SHADOW_MAP_BIT_INDEX + 1)
#define LIGHT_SHADOW_MAP_BIAS_MODE_BIT_COUNT 2
#define LIGHT_SHADOW_MAP_BIAS_MODE_MASK (((1 << LIGHT_SHADOW_MAP_BIAS_MODE_BIT_COUNT) - 1) << LIGHT_SHADOW_MAP_BIAS_MODE_BIT_INDEX)
#define LIGHT_SHADOW_MAP_BIAS_MODE_NONE (0x0 << LIGHT_SHADOW_MAP_BIAS_MODE_BIT_INDEX)
#define LIGHT_SHADOW_MAP_BIAS_MODE_OFFSET (0x1 << LIGHT_SHADOW_MAP_BIAS_MODE_BIT_INDEX)
#define LIGHT_SHADOW_MAP_BIAS_MODE_FLOAT_MULT (0x2 << LIGHT_SHADOW_MAP_BIAS_MODE_BIT_INDEX)
#define LIGHT_SHADOW_MAP_BIAS_MODE_FLOAT_ADD (0x3 << LIGHT_SHADOW_MAP_BIAS_MODE_BIT_INDEX)
#define LIGHT_SHADOW_MAP_BIAS_INCLUDE_THETA_BIT (0x1 << (LIGHT_SHADOW_MAP_BIAS_MODE_BIT_INDEX + LIGHT_SHADOW_MAP_BIAS_MODE_BIT_COUNT))

#define LIGHT_BLACK_BODY_EMISSION_BIT_INDEX (LIGHT_SHADOW_MAP_BIAS_MODE_BIT_INDEX + LIGHT_SHADOW_MAP_BIAS_MODE_BIT_COUNT + 1)
#define LIGHT_BLACK_BODY_EMISSION_BIT_FLAG (0x1 << LIGHT_BLACK_BODY_EMISSION_BIT_INDEX)

#define LIGHT_FLAGS_POS 16
#define LIGHT_FLAG_ATTENUATION_MASK (0x3 << LIGHT_FLAGS_POS)
#define LIGHT_FLAG_ATTENUATION_LINEAR (0x1 << LIGHT_FLAGS_POS)
#define LIGHT_FLAG_ATTENUATION_QUADRATIC (0x2 << LIGHT_FLAGS_POS)
#define LIGHT_FLAG_ATTENUATION_INSIDE (0x3 << LIGHT_FLAGS_POS)


#define POINT_LIGHT_DEFAULT_Z_NEAR 0.1