// A table to check what can be implicitely defined.
// See src/Core/Execution/ResourcesManager for explicit common definitions
// Also see src/Core/Rendering/DebugRenderer for debug related common definitions
#error "DO NOT INCLUDE THIS FILE!!!"

#define SHADER_SEMANTIC_VERTEX 1
#define SHADER_SEMANTIC_FRAGMENT 1
#define SHADER_SEMANTIC_GEOMETRY 1
#define SHADER_SEMANTIC_TESSELLATION_CONTROL 1
#define SHADER_SEMANTIC_TESSELLATION_EVALUATION 1
#define SHADER_SEMANTIC_TASK 1
#define SHADER_SEMANTIC_MESH 1
#define SHADER_SEMANTIC_COMPUTE 1
#define SHADER_SEMANTIC_RAYGEN 1
#define SHADER_SEMANTIC_INTERSECTION 1
#define SHADER_SEMANTIC_ANY_HIT 1
#define SHADER_SEMANTIC_CLOSEST_HIT 1
#define SHADER_SEMANTIC_MISS 1
#define SHADER_SEMANTIC_CALLABLE 1
#define SHADER_SEMANTIC_ 1

#define SHADER_FP16_AVAILABLE 1

#define SHADER_RAY_QUERY_AVAILABLE 1
#define SHADER_RAY_TRACING_AVAILABLE 1


#define GLOBAL_ENABLE_GLSL_DEBUG 1
#define SHADER_STRING_CAPACITY 32
#define DEBUG_BUFFER_STRING_SIZE 32
#define BUFFER_STRING_CAPACITY 32
#define GLYPH_SIZE 1
#define DEFAULT_FLOAT_PRECISION 3
#define DEFAULT_SHOW_PLUS true
#define DEBUG_BUFFER_STRINGS_CAPACITY 16
#define DEBUG_BUFFER_LINES_CAPACITY 16














