#pragma once

#ifndef BIND_SCENE
#define BIND_SCENE 0
#endif

#ifndef BIND_ALL_SCENE_COMPONENTS
#define BIND_ALL_SCENE_COMPONENTS 0
#endif

#define SCENE_OBJECT_FLAG_VISIBLE_BIT 1

#define SCENE_BINDING SCENE_DESCRIPTOR_BINDING + 0

#ifndef SCENE_DEFAULT_ACCESS
#if _slang
#define SCENE_DEFAULT_ACCESS ROM
#elif _glsl
#define SCENE_DEFAULT_ACCESS readonly
#endif
#endif

#define SCENE_LIGHTS_BINDING SCENE_BINDING + 1
#define SCENE_LIGHTS_NUM_BINDING 3

#define SCENE_OBJECTS_BINDING SCENE_LIGHTS_BINDING + SCENE_LIGHTS_NUM_BINDING
#define SCENE_OBJECTS_NUM_BINDING 1

#define SCENE_MESHS_BINDING SCENE_OBJECTS_BINDING + SCENE_OBJECTS_NUM_BINDING
#define SCENE_MESHS_NUM_BINDING 3

#define SCENE_MATERIAL_BINDING SCENE_MESHS_BINDING + SCENE_MESHS_NUM_BINDING
#define SCENE_MATERIAL_NUM_BINDING 2

#define SCENE_TEXTURES_BINDING SCENE_MATERIAL_BINDING + SCENE_MATERIAL_NUM_BINDING
#define SCENE_TEXTURES_NUM_BINDING 1

#define SCENE_XFORM_BINDING SCENE_TEXTURES_BINDING + SCENE_TEXTURES_NUM_BINDING
#define SCENE_XFORM_NUM_BINDING 2

#define SCENE_TLAS_BINDING SCENE_XFORM_BINDING + SCENE_XFORM_NUM_BINDING
#define SCENE_TLAS_NUM_BINDING 1


#define SCENE_MAX_BINDING SCENE_TLAS_BINDING + SCENE_TLAS_NUM_BINDING


#if BIND_ALL_SCENE_COMPONENTS

#ifndef SCENE_LIGHTS_ACCESS
#define SCENE_LIGHTS_ACCESS SCENE_DEFAULT_ACCESS
#endif

#ifndef SCENE_OBJECTS_ACCESS
#define SCENE_OBJECTS_ACCESS SCENE_DEFAULT_ACCESS
#endif

#ifndef SCENE_MESH_ACCESS 
#define SCENE_MESH_ACCESS SCENE_DEFAULT_ACCESS
#endif

#ifndef SCENE_MATERIAL_ACCESS
#define SCENE_MATERIAL_ACCESS SCENE_DEFAULT_ACCESS
#endif

#ifndef SCENE_TEXTURE_ACCESS
#define SCENE_TEXTURE_ACCESS SCENE_DEFAULT_ACCESS
#endif

#ifndef SCENE_XFORM_ACCESS
#define SCENE_XFORM_ACCESS SCENE_DEFAULT_ACCESS
#endif

#ifndef BIND_SCENE_TEXTURES
#define BIND_SCENE_TEXTURES 1
#endif

#ifndef BIND_SCENE_TLAS
#define BIND_SCENE_TLAS 1
#endif

#endif

#define SCENE_TEXTURE_ID_PER_MATERIAL 8

