import sys
from pathlib import Path

root_dir = Path(__file__).parent.parent
sys.path.append(str(root_dir))
scripts_dir = root_dir.joinpath("ext").joinpath("VulkanDocs").joinpath("scripts")
sys.path.append(str(scripts_dir))

from ext.VulkanDocs.scripts.base_generator import (BaseGenerator, BaseGeneratorOptions, SetTargetApiName, SetMergedApiNames, write)
from ext.VulkanDocs.scripts.reg import Registry

from ext.VulkanDocs.scripts import vulkan_object

from xml.etree import ElementTree

# Borrowed from Vulkan Utility Library
class PlatformGuardHelper():
	"""Used to elide platform guards together, so redundant #endif then #ifdefs are removed
	Note - be sure to call add_guard(None) when done to add a trailing #endif if needed
	"""
	def __init__(self):
		self.current_guard = None

	def add_guard(self, guard, extra_newline = False):
		out = []
		if self.current_guard != guard and self.current_guard is not None:
			out.append(f'#endif  // {self.current_guard}')
		if extra_newline:
			out.append('')
		if self.current_guard != guard and guard is not None:
			out.append(f'#ifdef {guard}')
		self.current_guard = guard
		return out

CONSTEVAL = 'VKU_CXX_20_CONSTEVAL'
DEFINE_CONSTEVAL = f'''\
#ifndef {CONSTEVAL}
#if __cpp_consteval
#define {CONSTEVAL} consteval
#elif __cpp_constexpr
#define {CONSTEVAL} constexpr
#else
#define {CONSTEVAL} inline
#endif
#endif
'''

CONSTINIT = 'VKU_CXX_20_CONSTINIT'
DEFINE_CONSTINIT = f'''\
#ifndef {CONSTINIT}
#if __cpp_constinit
#define {CONSTINIT} constinit
#elif __cpp_constexpr
#define {CONSTINIT} constexpr
#else
#define {CONSTINIT} inline
#endif
#endif
'''
class CStyleWriter:

	def __init__(self, indentation = '    ', open_block_inline = False, pragma_once = False, generator = None):
		self.out = []
		self.indent = 0
		self.indentation = indentation
		self.open_block_inline = open_block_inline
		if pragma_once:
			self.append("#pragma once")
		if generator is not None:
			self.append(f'''// *** THIS FILE IS GENERATED - DO NOT EDIT ***
// Generated by scripts/{generator}.py
''')

	def inc(self, count : int = 1):
		self.indent += count
	
	def dec(self, count : int = 1):
		self.inc(-count)

	def append(self, block : str | list[str], split = True, indent = None):
		if type(block) is list:
			for statement in block:
				self.append(statement, split=split, indent=indent)
			return
		elif type(block) is str:
			if split:
				self.append(block.split('\n'), split=False, indent=indent)
			else:
				if len(block) == 0:
					self.out.append('')
				else:
					if indent is None:
						indent = self.indentation * self.indent
					self.out.append(f'{indent}{block}')
		elif type(block) is CStyleWriter:
			self.append(block.out, split, indent=indent)
		else:
			raise NotImplementedError(f'Writer::append expects a str or list[str], not {str(type(block))}!')
	
	def open(self, block, opening = '{'):
		self.append(block)
		if opening is not None:
			self.append(opening)
		self.inc()

	def close(self, closing = '}'):
		self.dec()
		if closing is not None:
			self.append(closing)
		pass

	def __str__(self):
		return '\n'.join(self.out)

def ExtractExtensionTag(ext : vulkan_object.Extension):
	res = ext.name.split('_')[1]
	return res

def DefaultRegistryPath():
	return root_dir.joinpath("ext").joinpath("VulkanDocs").joinpath("xml").joinpath("vk.xml")

def DefaultGeneratedDir(root_dir):
	return root_dir.joinpath("vkl").joinpath("Generated")

def DefaultOutSourceDir():
	return DefaultGeneratedDir(root_dir.joinpath("src"))

def DefaultOutHeaderDir():
	return DefaultGeneratedDir(root_dir.joinpath("include"))

def MemberIs_sType(member : vulkan_object.Member):
	return member.name == 'sType' and member.type == 'VkStructureType'

def MemberIs_pNext(member : vulkan_object.Member):
	return member.name == 'pNext' and member.type == 'void'

class CommonBaseGenerator(BaseGenerator):

	def __init__(self):
		super().__init__()
		self.out_header_dir = None
		self.out_source_dir = None

	def writeTo(self, content, filepath):
		if filepath is not None:
			file = open(filepath, mode='w', encoding='utf-8', newline='\n')
		else:
			file = sys.stdout
		write(content, file=file)
	
	def setHeaderDir(self, dir):
		self.out_header_dir = dir
	
	def setSourceDir(self, dir):
		self.out_source_dir = dir

	def writeHeader(self, content, filename):
		self.writeTo(content, self.out_header_dir.joinpath(filename))

	def writeSource(self, content, filename):
		self.writeTo(content, self.out_source_dir.joinpath(filename))

	def getDefaultFileName(self):
		raise NotImplementedError()


def RunGenerator(GeneratorType, target=None, registry=DefaultRegistryPath(), outHeaderDir = DefaultOutHeaderDir(), outSourceDir = DefaultOutSourceDir()):
	SetTargetApiName("vulkan")
	SetMergedApiNames(None)

	gen = GeneratorType()

	if isinstance(gen, CommonBaseGenerator):
		gen.setHeaderDir(outHeaderDir)
		gen.setSourceDir(outSourceDir)

	if target is None:
		target = gen.getDefaultFileName()

	options = BaseGeneratorOptions(customFileName = target, customDirectory = outHeaderDir)

	reg = Registry(gen, options)

	# Parse the specified registry XML into an ElementTree object
	tree = ElementTree.parse(registry)

	# Load the XML tree into the registry object
	reg.loadElementTree(tree)

	# Finally, use the output generator to create the requested target
	reg.apiGen()