
from common import *

class EnumMetaGenerator(BaseGenerator):

	def __init__(self):
		super().__init__()
		self.max_prefix_len = 0
		self.max_value_len = 0
		self.max_name_len = 0
		self.id_counter = 0
		self.value_prefix_trailing_underscore = False

	def convertEnumNameToEnumPrefix(self, enum_name : str, digit_version : int | None):
		res = ''
		# HACK 'AV1' would be incorectly converted to 'A_V1',
		enum_name = enum_name.replace('AV1', 'Av1')
		for c in enum_name:
			if c.isupper() and len(res) != 0:
				res += '_'
			res += c.upper()
		if digit_version is not None:
			res += f'_{digit_version}'
		if self.value_prefix_trailing_underscore:
			res += '_'
		return res

	def extractValuePrefix(self, enum : vulkan_object.Enum, enum_type : type):
		if enum.name == 'VkResult':
			return 'VK_' if self.value_prefix_trailing_underscore else 'VK'
		res = enum.name
		is_bitfield = enum_type is vulkan_object.Bitmask
		exts = []
		for ext_name in enum.extensions:
			ext = self.vk.extensions[ext_name]
			exts.append(ExtractExtensionTag(ext))
		for ext in exts:
			ext_find = res.rfind(ext)
			if ext_find != -1:
				res = res.removesuffix(ext)
				break
		digit_version = None
		if is_bitfield:
			last_digit = res[-1]
			if last_digit.isdigit():
				digit_version = int(last_digit)
				res = res.removesuffix(last_digit)
			suffix = 'FlagBits'
			assert res.rfind(suffix) == len(res) - len(suffix)
			res = res.removesuffix(suffix)

		res = self.convertEnumNameToEnumPrefix(res, digit_version)
		return res

	def generateEnum(self, out : CStyleWriter, enum, enum_type : type):
		guard = PlatformGuardHelper()
		is_enum = enum_type is vulkan_object.Enum
		is_bitfield = enum_type is vulkan_object.Bitmask
		known_bits = 0
		assert is_enum != is_bitfield
		if is_enum:
			fields = enum.fields
		elif is_bitfield:
			fields = enum.flags

		value_prefix = self.extractValuePrefix(enum, enum_type)
		self.max_prefix_len = max(self.max_prefix_len, len(value_prefix))
		self.max_name_len = max(self.max_name_len, len(enum.name))
		out.open(f'''\
template<>
struct EnumMetaInfo<{enum.name}>\
''')
		out.append(f'''\
static {CONSTINIT} const bool IsBitField = {'true' if is_bitfield else 'false'};
static {CONSTINIT} const unsigned int UniqueId = {self.id_counter};
using EnumType = {enum.name};
static constexpr const char* const Name = "{enum.name}";
static constexpr const char* const ValuePrefix = "{value_prefix}";\
''')
		self.id_counter += 1
		out.open(f'static constexpr const char* GetValueName({enum.name} value)')
		out.append('const char* res = nullptr;')
		out.open('switch(value)')

		for field in fields:
			out.append(guard.add_guard(field.protect), indent='')
			if field.name.find(value_prefix) != 0:
				print(f'Warning, {field.name} does not begin with enum {enum.name} prefix {value_prefix}')
			value_str = field.name[len(value_prefix) + (0 if self.value_prefix_trailing_underscore else 1):]
			self.max_value_len = max(self.max_value_len, len(value_str))
			out.append(f'case {field.name}: res = "{value_str}"; break;')
		out.append(guard.add_guard(None), indent='')
		out.close() # switch
		out.append('return res;')
		out.close() # function
		out.close('};') # struct

	def generateCollection(self, out, col, enum_type : type):
		
		guard = PlatformGuardHelper()
		for enum in col.values():
			out.append(guard.add_guard(enum.protect), indent='')
			self.generateEnum(out, enum, enum_type)
		out.append(guard.add_guard(None), indent='')

	def generate(self):
		out = CStyleWriter(pragma_once=True, generator=__file__)

		out.append("#pragma once")
		out.append(f'''// *** THIS FILE IS GENERATED - DO NOT EDIT ***
// Generated by scripts/EnumMetaGenerator.py
''')
		out.append("#include <vkl/VkObjects/VulkanEnumMetaBase.hpp>")
		out.append(DEFINE_CONSTINIT, indent='')
		out.append(DEFINE_CONSTEVAL, indent='')
		out.open('''namespace vku''')

		self.generateCollection(out, self.vk.enums, vulkan_object.Enum)
		self.generateCollection(out, self.vk.bitmasks, vulkan_object.Bitmask)

		out.append(f'static {CONSTINIT} const unsigned int MaxEnumNameLen = {self.max_name_len};')
		out.append(f'static {CONSTINIT} const unsigned int MaxEnumPrefixLen = {self.max_prefix_len};')
		out.append(f'static {CONSTINIT} const unsigned int MaxEnumValueLen = {self.max_value_len};')
		out.append(f'static {CONSTINIT} const unsigned int EnumUniqueIdCount = {self.id_counter};')
		out.close('} // namespace vku')
		self.write(str(out))

	def getDefaultFileName(self):
		return "VulkanEnumMeta.hpp"
