
from common import *

class TypeHelperGenerator(BaseGenerator):

	def __init__(self):
		BaseGenerator.__init__(self)

	def generate(self):
		out = CStyleWriter()

		out.append("#pragma once")
		out.append(f'''// *** THIS FILE IS GENERATED - DO NOT EDIT ***
// Generated by scripts/TypeHelperGenerator.py
''')
		out.append('#include <vulkan/vulkan.h>')
		out.append('''
#ifndef VKU_CXX_20_CONSTEVAL
#if __cpp_consteval
#define VKU_CXX_20_CONSTEVAL consteval
#elif __cpp_constexpr
#define VKU_CXX_20_CONSTEVAL constexpr
#else
#define VKU_CXX_20_CONSTEVAL inline
#endif
#endif
''')
		out.open('''namespace vku2// Avoid conflict with current definitions in vku''')

		out.append(f'template <class VkHandle> static VKU_CXX_20_CONSTEVAL VkObjectType GetObjectType();')
		out.append('')
		guard = PlatformGuardHelper()
		for handle in self.vk.handles.values():
			out.append(guard.add_guard(handle.protect), indent='')
			out.append(f'template <> static VKU_CXX_20_CONSTEVAL VkObjectType GetObjectType<{handle.name}>() {{return {handle.type}; }}')
		out.append(guard.add_guard(None), indent='')

		out.append('', indent='')

		out.append(f'template <class VkStruct> static VKU_CXX_20_CONSTEVAL VkStructureType GetSType();')
		for struct in self.vk.structs.values():
			if struct.sType is not None:
				out.append(guard.add_guard(struct.protect), indent='')
				out.append(f'template <> static VKU_CXX_20_CONSTEVAL VkStructureType GetSType<{struct.name}>() {{return {struct.sType}; }}')
		out.append(guard.add_guard(None), indent='')

		out.close('} // namespace vku2')
		self.write(str(out))

	def getDefaultFileName(self):
		return "VulkanTypeStructHelper.hpp"
