#pragma once

#define DEBUG_ENABLE_MASK	0x1
#define DEBUG_ENABLE_BIT	0x1

#define DEBUG_SPACE_MASK		(0x3 << 1)
#define DEBUG_CLIP_SPACE_BIT	(0x0 << 1)
#define DEBUG_UV_SPACE_BIT		(0x1 << 1)
#define DEBUG_PIXEL_SPACE_BIT	(0x2 << 1)

#ifndef GLYPH_SIZE_PIX
#define GLYPH_SIZE_PIX vec2(16, 16)
#endif

#define GLYPH_SIZE_TINY -2
#define GLYPH_SIZE_SMALL -1
#define GLYPH_SIZE_NORMAL 0
#define GLYPH_SIZE_LARGE 1
#define GLYPH_SIZE_HUGE 2

#define FONT_SIZE_TINY GLYPH_SIZE_TINY
#define FONT_SIZE_SMALL GLYPH_SIZE_SMALL
#define FONT_SIZE_NORMAL GLYPH_SIZE_NORMAL
#define FONT_SIZE_LARGE GLYPH_SIZE_LARGE
#define FONT_SIZE_HUGE GLYPH_SIZE_HUGE 

#ifndef GLYPH_SIZE
#define GLYPH_SIZE GLYPH_SIZE_NORMAL
#endif

#define DEFAULT_FONT_SIZE GLYPH_SIZE


#ifndef DEBUG_BUFFER_BINDING
#define DEBUG_BUFFER_BINDING COMMON_DESCRIPTOR_BINDING
#endif


#ifndef BIND_DEBUG_BUFFERS
#define BIND_DEBUG_BUFFERS (I_WANT_TO_DEBUG & GLOBAL_ENABLE_SHADER_DEBUG)
#endif






